# Just for tests
BPS:
  threadsForInvoiceObserver: 2

invoiceProcessor:
  frequency: 5000

paymentProcessor:
  frequency: 3000

database:
  connectionURL: "jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;"
  driver: "org.h2.Driver"
  maximumPoolSize: 5

# Enabled currencies
# Supported —Åurrencies: BTC, XRP, TRX
enabledCurrencies:
  coins:
    - BTC
    - XRP
    - TRX

# Example values
BTC:
  coin:
    user: "user"
    password: "password"
    confirmations: 1
  connection:
    host: "127.0.0.1"
    port: "18443"
  explorer:
    frequency: 5000

TRX:
  coin:
    # Base58Checksum representation of account
    account: "TW4hF7TVhme1STRC2NToDA41RxCx1H2HbS"
    accountAddress: "41dc6c2bc46639e5371fe99e002858754604cf5847"
    privateKey: "92f451c194301b4a1eae3a818cc181e1a319656dcdf6760cdbe35c54b05bb3ec"
    confirmations: 3
  connection:
    host: "127.0.0.1"
    port: "18190"
  explorer:
    frequency: 3000

XRP:
  coin:
    account: "rHb9CJAWyB4rj91VRWn96DkukG4bwdtyTh"
    privateKey: "snoPBrXtMeMyMHUVTgbuqAfg1SUTb"
    passPhrase: "masterpassphrase"
  connection:
    host: "127.0.0.1"
    port: "51234"
  explorer:
    frequency: 5000